### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by monemihir**
Removed blanket lowercase conversion for filenames.

Relates to issue #10.

### CODE REVIEW

**Comment by Neamar** [comment]
Thanks!

**Comment by Neamar** [comment]
(test suite updated in 690621e)

**Comment by Neamar** [comment]
Published! https://github.com/Neamar/auto-load/releases/tag/v3.0.0

**Comment by monemihir** [comment]
Works now. Cheers mate.


________________________________

**Pull request merged**
